# Generated by Django 3.1.5 on 2021-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_client',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
