# Generated by Django 3.1.5 on 2021-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210401_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_client',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
