# Generated by Django 3.1.5 on 2021-04-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20210401_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_client')),
            ],
            options={
                'db_table': 'tbl_project',
            },
        ),
    ]
