# Generated by Django 3.1.5 on 2021-04-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('userapp', '0004_tbl_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_project_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tbl_project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_user')),
            ],
            options={
                'db_table': 'tbl_project_user',
            },
        ),
    ]
